CREATE SCHEMA IF NOT EXISTS normalized;

CREATE TABLE normalized.area_type (
    area_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL
);

CREATE TABLE normalized.zone_type (
    zone_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL
);

CREATE TABLE normalized.camera_status (
    camera_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL
);

CREATE TABLE normalized.event_type (
    event_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    description TEXT
);

CREATE TABLE normalized.event_severity (
    event_severity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    rank SMALLINT NOT NULL UNIQUE
);

CREATE TABLE normalized.object_type (
    object_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL
);

CREATE TABLE normalized.direction (
    direction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL
);

CREATE TABLE normalized.video_codec (
    video_codec_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL
);

CREATE TABLE normalized.signal_lost_reason (
    signal_lost_reason_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL
);

CREATE TABLE normalized.area (
    area_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_type_id BIGINT NOT NULL REFERENCES normalized.area_type(area_type_id),
    area_code VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    address TEXT,
    description TEXT
);

CREATE TABLE normalized.zone (
    zone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id BIGINT NOT NULL REFERENCES normalized.area(area_id) ON DELETE CASCADE,
    zone_type_id BIGINT NOT NULL REFERENCES normalized.zone_type(zone_type_id),
    zone_code VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    importance_level SMALLINT NOT NULL,
    description TEXT,
    UNIQUE (area_id, zone_code)
);

CREATE TABLE normalized.camera (
    camera_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT NOT NULL REFERENCES normalized.zone(zone_id),
    camera_status_id BIGINT NOT NULL REFERENCES normalized.camera_status(camera_status_id),
    serial_number VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    model VARCHAR NOT NULL,
    ip_address INET NOT NULL UNIQUE,
    position_x NUMERIC NOT NULL,
    position_y NUMERIC NOT NULL,
    position_z NUMERIC NOT NULL,
    yaw_angle NUMERIC NOT NULL,
    pitch_angle NUMERIC NOT NULL,
    roll_angle NUMERIC NOT NULL,
    view_angle NUMERIC NOT NULL
);

CREATE TABLE normalized.camera_stream_setting (
    camera_id BIGINT PRIMARY KEY REFERENCES normalized.camera(camera_id) ON DELETE CASCADE,
    video_codec_id BIGINT NOT NULL REFERENCES normalized.video_codec(video_codec_id),
    resolution_width INTEGER NOT NULL,
    resolution_height INTEGER NOT NULL,
    fps INTEGER NOT NULL,
    bitrate_kbps INTEGER NOT NULL,
    rtsp_enabled BOOLEAN NOT NULL
);

CREATE TABLE normalized.camera_analytics_setting (
    camera_id BIGINT PRIMARY KEY REFERENCES normalized.camera(camera_id) ON DELETE CASCADE,
    motion_detection BOOLEAN NOT NULL,
    line_crossing BOOLEAN NOT NULL,
    object_detection BOOLEAN NOT NULL,
    sensitivity NUMERIC NOT NULL,
    min_object_confidence NUMERIC NOT NULL
);

CREATE TABLE normalized.camera_detection_zone (
    camera_detection_zone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_id BIGINT NOT NULL REFERENCES normalized.camera(camera_id) ON DELETE CASCADE,
    detection_zone_code VARCHAR NOT NULL,
    UNIQUE (camera_id, detection_zone_code)
);

CREATE TABLE normalized.camera_detection_zone_point (
    detection_zone_point_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_detection_zone_id BIGINT NOT NULL REFERENCES normalized.camera_detection_zone(camera_detection_zone_id) ON DELETE CASCADE,
    point_order INTEGER NOT NULL,
    x NUMERIC NOT NULL,
    y NUMERIC NOT NULL,
    UNIQUE (camera_detection_zone_id, point_order)
);

CREATE TABLE normalized.camera_crossing_line (
    camera_crossing_line_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_id BIGINT NOT NULL REFERENCES normalized.camera(camera_id) ON DELETE CASCADE,
    allowed_direction_id BIGINT NOT NULL REFERENCES normalized.direction(direction_id),
    line_code VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    start_x NUMERIC NOT NULL,
    start_y NUMERIC NOT NULL,
    end_x NUMERIC NOT NULL,
    end_y NUMERIC NOT NULL,
    UNIQUE (camera_id, line_code)
);

CREATE TABLE normalized.event (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT NOT NULL REFERENCES normalized.zone(zone_id),
    event_type_id BIGINT NOT NULL REFERENCES normalized.event_type(event_type_id),
    event_severity_id BIGINT NOT NULL REFERENCES normalized.event_severity(event_severity_id),
    event_number BIGINT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    confidence NUMERIC NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    UNIQUE (zone_id, event_number)
);

CREATE TABLE normalized.event_camera (
    event_id BIGINT NOT NULL REFERENCES normalized.event(event_id) ON DELETE CASCADE,
    camera_id BIGINT NOT NULL REFERENCES normalized.camera(camera_id),
    PRIMARY KEY (event_id, camera_id)
);

CREATE TABLE normalized.motion_event_detail (
    event_id BIGINT PRIMARY KEY REFERENCES normalized.event(event_id) ON DELETE CASCADE,
    camera_detection_zone_id BIGINT REFERENCES normalized.camera_detection_zone(camera_detection_zone_id),
    frame_time_ms INTEGER NOT NULL,
    motion_area_percent NUMERIC NOT NULL,
    duration_ms INTEGER NOT NULL
);

CREATE TABLE normalized.object_detection_event_detail (
    event_id BIGINT PRIMARY KEY REFERENCES normalized.event(event_id) ON DELETE CASCADE,
    frame_time_ms INTEGER NOT NULL
);

CREATE TABLE normalized.line_crossing_event_detail (
    event_id BIGINT PRIMARY KEY REFERENCES normalized.event(event_id) ON DELETE CASCADE,
    camera_crossing_line_id BIGINT NOT NULL REFERENCES normalized.camera_crossing_line(camera_crossing_line_id),
    direction_id BIGINT NOT NULL REFERENCES normalized.direction(direction_id),
    frame_time_ms INTEGER NOT NULL
);

CREATE TABLE normalized.signal_lost_event_detail (
    event_id BIGINT PRIMARY KEY REFERENCES normalized.event(event_id) ON DELETE CASCADE,
    signal_lost_reason_id BIGINT NOT NULL REFERENCES normalized.signal_lost_reason(signal_lost_reason_id),
    last_frame_at TIMESTAMPTZ NOT NULL,
    downtime_seconds INTEGER NOT NULL
);

CREATE TABLE normalized.detected_object (
    detected_object_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES normalized.event(event_id) ON DELETE CASCADE,
    object_type_id BIGINT NOT NULL REFERENCES normalized.object_type(object_type_id),
    object_number INTEGER NOT NULL,
    confidence NUMERIC NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    bounding_box_x INTEGER NOT NULL,
    bounding_box_y INTEGER NOT NULL,
    bounding_box_width INTEGER NOT NULL,
    bounding_box_height INTEGER NOT NULL,
    UNIQUE (event_id, object_number)
);

CREATE TABLE normalized.person_object_attribute (
    detected_object_id BIGINT PRIMARY KEY REFERENCES normalized.detected_object(detected_object_id) ON DELETE CASCADE,
    direction_id BIGINT REFERENCES normalized.direction(direction_id),
    has_bag BOOLEAN,
    clothing_color VARCHAR
);

CREATE TABLE normalized.vehicle_object_attribute (
    detected_object_id BIGINT PRIMARY KEY REFERENCES normalized.detected_object(detected_object_id) ON DELETE CASCADE,
    color VARCHAR,
    license_plate VARCHAR,
    license_plate_confidence NUMERIC
);

CREATE TABLE normalized.camera_telemetry (
    camera_id BIGINT NOT NULL REFERENCES normalized.camera(camera_id) ON DELETE CASCADE,
    recorded_at TIMESTAMPTZ NOT NULL,
    camera_status_id BIGINT NOT NULL REFERENCES normalized.camera_status(camera_status_id),
    temperature_celsius NUMERIC,
    cpu_load NUMERIC,
    memory_usage NUMERIC,
    bitrate_kbps INTEGER,
    packet_loss NUMERIC,
    latency_ms INTEGER,
    uptime_seconds BIGINT,
    PRIMARY KEY (camera_id, recorded_at)
);

INSERT INTO normalized.area_type (code, name) VALUES
    ('office', 'Office'),
    ('warehouse', 'Warehouse'),
    ('parking', 'Parking'),
    ('campus', 'Campus'),
    ('industrial_site', 'Industrial site');

INSERT INTO normalized.zone_type (code, name) VALUES
    ('entrance', 'Entrance'),
    ('parking', 'Parking'),
    ('warehouse', 'Warehouse'),
    ('perimeter', 'Perimeter'),
    ('service_room', 'Service room');

INSERT INTO normalized.camera_status (code, name) VALUES
    ('active', 'Active'),
    ('offline', 'Offline'),
    ('maintenance', 'Maintenance'),
    ('signal_lost', 'Signal lost');

INSERT INTO normalized.event_type (code, name, description) VALUES
    ('motion_detected', 'Motion detected', 'Motion was detected in a camera detection zone'),
    ('object_detected', 'Object detected', 'One or more objects were detected in a frame'),
    ('line_crossing', 'Line crossing', 'An object crossed a configured line'),
    ('signal_lost', 'Signal lost', 'Camera video signal was lost');

INSERT INTO normalized.event_severity (code, name, rank) VALUES
    ('low', 'Low', 1),
    ('medium', 'Medium', 2),
    ('high', 'High', 3),
    ('critical', 'Critical', 4);

INSERT INTO normalized.object_type (code, name) VALUES
    ('person', 'Person'),
    ('vehicle', 'Vehicle'),
    ('unknown', 'Unknown');

INSERT INTO normalized.direction (code, name) VALUES
    ('inside', 'Inside'),
    ('outside', 'Outside'),
    ('left_to_right', 'Left to right'),
    ('right_to_left', 'Right to left'),
    ('unknown', 'Unknown');

INSERT INTO normalized.video_codec (code, name) VALUES
    ('H.264', 'H.264'),
    ('H.265', 'H.265'),
    ('MJPEG', 'MJPEG');

INSERT INTO normalized.signal_lost_reason (code, name) VALUES
    ('network_timeout', 'Network timeout'),
    ('power_off', 'Power off'),
    ('stream_error', 'Stream error');
