CREATE SCHEMA IF NOT EXISTS jsonb;

CREATE TABLE jsonb.area (
    area_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_code VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    area_type VARCHAR NOT NULL CHECK (area_type IN ('office', 'warehouse', 'parking', 'campus', 'industrial_site')),
    address TEXT,
    description TEXT
);

CREATE TABLE jsonb.zone (
    zone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id BIGINT NOT NULL REFERENCES jsonb.area(area_id) ON DELETE CASCADE,
    zone_code VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    zone_type VARCHAR NOT NULL CHECK (zone_type IN ('entrance', 'parking', 'warehouse', 'perimeter', 'service_room')),
    importance_level SMALLINT NOT NULL,
    description TEXT,
    UNIQUE (area_id, zone_code)
);

CREATE TABLE jsonb.camera (
    camera_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT NOT NULL REFERENCES jsonb.zone(zone_id) ON DELETE RESTRICT,
    serial_number VARCHAR NOT NULL UNIQUE,
    name VARCHAR NOT NULL,
    model VARCHAR NOT NULL,
    ip_address INET NOT NULL UNIQUE,
    status VARCHAR NOT NULL CHECK (status IN ('active', 'offline', 'maintenance', 'signal_lost')),
    position JSONB NOT NULL CHECK (jsonb_typeof(position) = 'object'),
    settings JSONB NOT NULL CHECK (jsonb_typeof(settings) = 'object')
);

CREATE TABLE jsonb.event (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id BIGINT NOT NULL REFERENCES jsonb.zone(zone_id) ON DELETE RESTRICT,
    event_number BIGINT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    event_type VARCHAR NOT NULL CHECK (event_type IN ('motion_detected', 'object_detected', 'line_crossing', 'signal_lost')),
    severity VARCHAR NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    confidence NUMERIC NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    payload JSONB NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
    UNIQUE (zone_id, event_number)
);

CREATE TABLE jsonb.event_camera (
    event_id BIGINT NOT NULL REFERENCES jsonb.event(event_id) ON DELETE CASCADE,
    camera_id BIGINT NOT NULL REFERENCES jsonb.camera(camera_id) ON DELETE RESTRICT,
    PRIMARY KEY (event_id, camera_id)
);

CREATE TABLE jsonb.camera_telemetry (
    camera_id BIGINT NOT NULL REFERENCES jsonb.camera(camera_id) ON DELETE CASCADE,
    recorded_at TIMESTAMPTZ NOT NULL,
    status VARCHAR NOT NULL CHECK (status IN ('active', 'offline', 'maintenance', 'signal_lost')),
    metrics JSONB NOT NULL CHECK (jsonb_typeof(metrics) = 'object'),
    PRIMARY KEY (camera_id, recorded_at)
);
