USE Lab10;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
-- SERIALIZABLE

BEGIN TRAN;

SELECT 'First read' AS Step, COUNT(*) AS Cnt
FROM Orders
WHERE Amount > 100;

-- Pause
WAITFOR DELAY '00:00:15';

SELECT 'Second read' AS Step, COUNT(*) AS Cnt
FROM Orders
WHERE Amount > 100;

COMMIT TRAN;
