from typing import Dict, List, Tuple

from grammar_parser import TokenType
from grammar_semantics import GrammarError, GrammarSymbol, Production
from table_builder import EPSILON_SYMBOL, ParseTable


def emit_python_table(
    table: ParseTable,
    output_filename: str,
    terminal_mode: str,
    table_name: str = "PARSE_TABLE",
) -> None:
    if terminal_mode not in ("enum", "string"):
        raise ValueError("terminal_mode must be 'enum' or 'string'")

    lines: List[str] = []
    lines.append("# This file was generated by generator.py")
    lines.append("# Do not edit it by hand.")
    lines.append("")

    if terminal_mode == "enum":
        lines.append("from grammar_parser import TokenType, EPSILON_SYMBOL")
        lines.append("")
    else:
        lines.append(f"EPSILON_SYMBOL = {EPSILON_SYMBOL!r}")
        lines.append("")

    lines.append(f"{table_name} = {{")

    for key in sorted(table.keys(), key=lambda item: (item[0], item[1])):
        left, lookahead = key
        production = table[key]
        rendered_key = render_key(left, lookahead, terminal_mode)
        rendered_right = render_right(production.right, terminal_mode)
        lines.append(f"    {rendered_key}: {rendered_right},")

    lines.append("}")
    lines.append("")

    with open(output_filename, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def render_key(left: str, lookahead: str, terminal_mode: str) -> str:
    return f"({left!r}, {render_terminal(lookahead, terminal_mode)})"


def render_right(symbols: List[GrammarSymbol], terminal_mode: str) -> str:
    if not symbols:
        return "[EPSILON_SYMBOL]"

    rendered_symbols = [render_symbol(symbol, terminal_mode) for symbol in symbols]
    return "[" + ", ".join(rendered_symbols) + "]"


def render_symbol(symbol: GrammarSymbol, terminal_mode: str) -> str:
    if symbol.is_terminal:
        return render_terminal(symbol.name, terminal_mode)
    return repr(symbol.name)


def render_terminal(name: str, terminal_mode: str) -> str:
    if terminal_mode == "string":
        return repr(name)

    if not hasattr(TokenType, name):
        raise GrammarError(
            f"Terminal {name!r} cannot be emitted as TokenType.{name}; "
            "use --mode string or rename the terminal"
        )
    return f"TokenType.{name}"
